Changes in the code so that it compiles
Original error:

`/usr/bin/ld: Formula/LTL/generalized.o:(.bss+0x10): multiple definition of `rank'; Formula/LTL/buchi.o:(.bss+0x0): first defined here
/usr/bin/ld: Formula/LTL/generalized.o:(.bss+0x38): multiple definition of `scc_stack'; Formula/LTL/buchi.o:(.bss+0x10): first defined here`